### ISSUE TITLE
How to get the variable genes_info in STAARpipeline_Gene_Centric_Coding.r

### ISSUE THREAD

**Issue by hmutanqilong** [xihaoli/STAARpipeline-Tutorial#1]
Hi, I am trying to learn this STAAR pipeline to deal with rare variant analysis. However, when I ran the Gene_Centric_Coding script, I found that I did not have the genes_info as the input file.  So, how to get the genes_info file.

```
###########################################################
#           Main Function 
###########################################################
## gene number in job
gene_num_in_array <- 50 
group.num.allchr <- ceiling(table(genes_info[,2])/gene_num_in_array)
sum(group.num.allchr)
```

**Comment by hmutanqilong** [comment]
OK, I have known if I load STAARpipeline, I will get the genes_info. Thanks!

**Comment by xihaoli** [comment]
Yes, `genes_info` is an object embedded in the STAARpipeline package. Please let me know if you have any other questions. Thanks!
