### ISSUE TITLE
Gene_Centric_Coding output ERROR messages

### ISSUE THREAD

**Issue by DamienTan** [xihaoli/STAARpipeline-Tutorial#14]
Hi Dr. Li 
Sorry to bother you again. I met some ERROR messages when I ran `Gene Centric Coding analysis`. Here are the part of the log file.
***
         used (Mb) gc trigger (Mb) max used (Mb)
Ncells 269062 14.4     654557   35   444157 23.8
Vcells 448534  3.5    8388608   64  1771722 13.6
[1] 379
[1] 51
\# of selected samples: 772
\# of selected variants: 280
\# of selected samples: 772
\# of selected variants: 6
\# of selected samples: 772
\# of selected variants: 0
Error in STAAR(Geno, obj_nullmodel, Anno.Int.PHRED.sub.category, rare_maf_cutoff = rare_maf_cutoff,  : 
  genotype is not a matrix!
\# of selected samples: 772
\# of selected variants: 0
Error in STAAR(Geno, obj_nullmodel, Anno.Int.PHRED.sub.category, rare_maf_cutoff = rare_maf_cutoff,  : 
  genotype is not a matrix!
\# of selected samples: 772
\# of selected variants: 1
Error in STAAR(Geno, obj_nullmodel, Anno.Int.PHRED.sub.category, rare_maf_cutoff = rare_maf_cutoff,  : 
  Number of rare variant in the set is less than 2!
\# of selected samples: 772
\# of selected variants: 5
\# of selected samples: 772
\# of selected variants: 0
Error in STAAR(Geno, obj_nullmodel, Anno.Int.PHRED.sub.category, rare_maf_cutoff = rare_maf_cutoff,  : 
  genotype is not a matrix!
\# of selected samples: 772
\# of selected variants: 3,197,953
[1] 52
\# of selected samples: 772
\# of selected variants: 24
\# of selected samples: 772
\# of selected variants: 6
\# of selected samples: 772
\# of selected variants: 0
Error in STAAR(Geno, obj_nullmodel, Anno.Int.PHRED.sub.category, rare_maf_cutoff = rare_maf_cutoff,  : 
  genotype is not a matrix!
\# of selected samples: 772
\# of selected variants: 0
Error in STAAR(Geno, obj_nullmodel, Anno.Int.PHRED.sub.category, rare_maf_cutoff = rare_maf_cutoff,  : 
  genotype is not a matrix!
\# of selected samples: 772
\ # of selected variants: 3
Error in STAAR(Geno, obj_nullmodel, Anno.Int.PHRED.sub.category, rare_maf_cutoff = rare_maf_cutoff,  : 
  Number of rare variant in the set is less than 2!
\# of selected samples: 772
\# of selected variants: 3
\# of selected samples: 772
\# of selected variants: 0
Error in STAAR(Geno, obj_nullmodel, Anno.Int.PHRED.sub.category, rare_maf_cutoff = rare_maf_cutoff,  : 
  genotype is not a matrix!
\# of selected samples: 772
\# of selected variants: 3,197,953
[1] 53
\# of selected samples: 772
\# of selected variants: 163
\# of selected samples: 772
\# of selected variants: 10
\# of selected samples: 772
\# of selected variants: 1
Error in STAAR(Geno, obj_nullmodel, Anno.Int.PHRED.sub.category, rare_maf_cutoff = rare_maf_cutoff,  : 
  Number of rare variant in the set is less than 2!
\# of selected samples: 772
\# of selected variants: 1
Error in STAAR(Geno, obj_nullmodel, Anno.Int.PHRED.sub.category, rare_maf_cutoff = rare_maf_cutoff,  : 
  Number of rare variant in the set is less than 2!
\# of selected samples: 772
\# of selected variants: 5
\# of selected samples: 772
\# of selected variants: 4
\# of selected samples: 772
\# of selected variants: 0
Error in STAAR(Geno, obj_nullmodel, Anno.Int.PHRED.sub.category, rare_maf_cutoff = rare_maf_cutoff,  : 
  genotype is not a matrix!
\# of selected samples: 772
\# of selected variants: 3,197,953
[1] 54
\# of selected samples: 772
\# of selected variants: 37
\# of selected samples: 772
\# of selected variants: 1
\# of selected samples: 772
\# of selected variants: 0
Error in STAAR(Geno, obj_nullmodel, Anno.Int.PHRED.sub.category, rare_maf_cutoff = rare_maf_cutoff,  : 
  genotype is not a matrix!
\# of selected samples: 772
\# of selected variants: 0
Error in STAAR(Geno, obj_nullmodel, Anno.Int.PHRED.sub.category, rare_maf_cutoff = rare_maf_cutoff,  : 
  genotype is not a matrix!
\# of selected samples: 772
\# of selected variants: 1
Error in STAAR(Geno, obj_nullmodel, Anno.Int.PHRED.sub.category, rare_maf_cutoff = rare_maf_cutoff,  : 
  Number of rare variant in the set is less than 2!
\# of selected samples: 772
\# of selected variants: 0
Error in STAAR(Geno, obj_nullmodel, Anno.Int.PHRED.sub.category, rare_maf_cutoff = rare_maf_cutoff,  : 
  genotype is not a matrix!
\# of selected samples: 772
\# of selected variants: 0
Error in STAAR(Geno, obj_nullmodel, Anno.Int.PHRED.sub.category, rare_maf_cutoff = rare_maf_cutoff,  : 
  genotype is not a matrix!
\# of selected samples: 772
\# of selected variants: 3,197,953
[1] 55
\# of selected samples: 772
\# of selected variants: 76
\# of selected samples: 772
\# of selected variants: 11
\# of selected samples: 772
\# of selected variants: 0
Error in STAAR(Geno, obj_nullmodel, Anno.Int.PHRED.sub.category, rare_maf_cutoff = rare_maf_cutoff,  : 
  genotype is not a matrix!
\# of selected samples: 772
\# of selected variants: 0
Error in STAAR(Geno, obj_nullmodel, Anno.Int.PHRED.sub.category, rare_maf_cutoff = rare_maf_cutoff,  : 
  genotype is not a matrix!
\# of selected samples: 772
\# of selected variants: 4
\# of selected samples: 772
\# of selected variants: 7
\# of selected samples: 772
\# of selected variants: 0
Error in STAAR(Geno, obj_nullmodel, Anno.Int.PHRED.sub.category, rare_maf_cutoff = rare_maf_cutoff,  : 
  genotype is not a matrix!
\# of selected samples: 772
\# of selected variants: 3,197,953
***

I don't know if the Error messages will interrupt the next steps. Could you give some advice?
Looking forward to yout reply.
Damien

**Comment by xihaoli** [comment]
Hi Damien,

Thanks for letting me know. I can confirm that these messages are not errors from your scripts, but they serve as indications of certain functional categories of genes that do not have at least 2 rare variants to form a variant set. Please feel free to go ahead; this will not interrupt the next steps.

Best,
Xihao

**Comment by DamienTan** [comment]
That is inspiring! Thanks so much for your reply.

**Comment by xihaoli** [comment]
You're very welcome, Damien!
