### ISSUE TITLE
Error in Gene_Centric_Coding analysis

### ISSUE THREAD

**Issue by pelinunal** [xihaoli/STAARpipeline-Tutorial#15]
Dear Xihao,

While I performed _Gene_Centric_Coding analysis_, the error below showed up and there were no outputs for some arrayid. 

```
Error in seqGetData(genofile, paste0(Annotation_dir, Annotation_name_catalog$dir[which(Annotation_name_catalog$name ==  : 
  The GDS node "annotation/info/FunctionalAnnotation/genecode_comprehensive_exonic_category" does not exist.
```
There was no output from every arrayid but I thought it might run the code with the existing output files. I performed the _STAARpipelineSummary Gene Centric Coding_ analysis and got this error:
```
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: Gene_Centric_Coding_Results_Summary -> get -> load -> readChar
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file '..../Gene_Centric_Coding_1.Rdata', probable reason 'No such file or direc$
Execution halted
```
I have the same problem with _Gene_Centric_Noncoding_, _Sliding Window_, and _Dynamic Window_ analysis. However, there was no problem with the individual analysis. 

I hope you can help me :)

Thank you!
Pelin

**Comment by xihaoli** [comment]
Hi Pelin,

Thank you for your questions. For _Gene_Centric_Coding analysis_, have you prepared your genotype and annotation data into a single AGDS file one per chromosome, following the FAVORannotator steps?

Best,
Xihao

**Comment by pelinunal** [comment]
Hi Xihao,
Thank you for your quick response! 

I have prepared the single aGDS file per chr by following your tutorial steps. I downloaded annotation data from FAVORannotator's database (containing 20 essential annotation scores) in CSV format​. However, it seems the problem is with some chunk chr files which are empty. Thank you made me notice! I will download again the FAVOR files and perform the analysis from the beginning.

Have a good day!
Bests,
Pelin

**Comment by xihaoli** [comment]
Hi Pelin,

You're very welcome. Before you re-download the FAVOR files, could you please do a quick check for one of your aGDS file that caused the issue of

`The GDS node "annotation/info/FunctionalAnnotation/genecode_comprehensive_exonic_category" does not exist`

You may check this by pasting the output here using
```
library(SeqArray)
genofile <- seqOpen("/path_to_the_file/chr1.gds") # suppose chromosome 1 aGDS file has the above issue
genofile
```

Best,
Xihao

**Comment by pelinunal** [comment]
Dear Xihao,

I have checked each chromosome aGDS file as you suggested and there is no error, all of them are readable as formal class SeqVarGDSClass.

Bests,
Pelin
