### ISSUE TITLE
"Coding mask" AND "Noncoding mask"

### ISSUE THREAD

**Issue by DamienTan** [xihaoli/STAARpipeline-Tutorial#17]
Dear Dr. Li
 I am confused with the `"Coding mask" AND "Noncoding mask"` in R script [STAARpipelineSummary_Gene_Centric_Coding_Annotation.r](https://github.com/xihaoli/STAARpipeline-Tutorial/blob/main/STAARpipelineSummary_Gene_Centric_Coding_Annotation.r) and [STAARpipelineSummary_Gene_Centric_Noncoding_Annotation.r](https://github.com/xihaoli/STAARpipeline-Tutorial/blob/main/STAARpipelineSummary_Gene_Centric_Noncoding_Annotation.r)

\## Chr
chr_seq <- c(1,7,19,19,9)
\## Gene name
gene_name_seq <- c("PCSK9","NPC1L1","LDLR","APOE","RNF20")
\## Coding mask
category_seq <- c("plof","missense","missense","missense","synonymous")

Why did you choose these five genes? If I want to run these annotation steps, should I choose other genes and how to choose these genes?
Looking forward to your reply.

**Comment by xihaoli** [comment]
Hi Damian,

Thanks for your question. These five genes and their categories (masks) are the ones that were significant in our analysis of lipid traits, so we listed them here as an example. For your case, please feel free to change them to your list of gene masks of interest. Note that `chr_seq`, `gene_name_seq`, `category_seq` should have the same length such that in our case, we were interested in querying the plof rare variants of _PCSK9_ (on chr 1); missense rare variants of _NPC1L1_ (on chr 7); missense rare variants of _LDLR_ (on chr 19); missense rare variants of _APOE_ (on chr 19); and synonymous rare variants of _RNF20_ (on chr 9).

Hope this is clear.

Best,
Xihao

**Comment by DamienTan** [comment]
Dear Dr. Li
Really apprecciate it!
It means that I can select the canditate genes in the previous analysis results and these genes are significant. By the way, should I select the top genes in manhattan plot as the input genes?

**Comment by xihaoli** [comment]
Hi Damien,

Yes, the [STAARpipelineSummary_Gene_Centric_Coding_Annotation.r](https://github.com/xihaoli/STAARpipeline-Tutorial/blob/main/STAARpipelineSummary_Gene_Centric_Coding_Annotation.r) function is general in the sense that you may use it to query any gene mask. However, in practice, you may select the candidate gene masks that were significant or suggestively significant in your unconditional analysis results, which were essentially the top gene masks in the manhattan plot as your input.

Best,
Xihao

**Comment by DamienTan** [comment]
Thanks again for your generous help, I got your point!

**Comment by xihaoli** [comment]
You are very welcome, Damien!

Best,
Xihao
