### ISSUE TITLE
info and tutorial files

### ISSUE THREAD

**Issue by nandobonf** [xihaoli/STAARpipeline-Tutorial#2]
Dear authors, 
I am trying to reproduce the analysis provided in this tutorial but it is a bit tricky without the same input files you used and/or a bit more explanations for reproducibility.
For example, in the "STAARpipeline_Null_Model.r" it is not clear how the covariates are coded, as well as the tested phenotype.
Also, it is not clear how the sparse GRM is produced from the gds file.
Thank you for the help.

**Comment by xihaoli** [comment]
Hi Ferdinando,

Thanks for reaching out. For your questions:

(1) In `STAARpipeline_Null_Model.r`, the `phenotype` object is an R data frame consisting of the sample id, covariates, and the tested phenotype. The rows of the data frame represent different individuals, and the columns represent different variables. An example of the `phenotype` object can be found [here](https://cran.r-project.org/web/packages/GMMAT/vignettes/GMMAT.pdf#page=7).

(2) The sparse GRM can be calculated using standard approaches. An example pipeline for producing the sparse GRM from the gds file can be found [here](https://uw-gac.github.io/SISG_2021/ancestry-and-relatedness-inference.html#computing-a-grm).

Please feel free to let me know if you have any additional questions. We are planning to include more explanations of the tutorial in the near future.

Best,
Xihao
