### ISSUE TITLE
Small number of variants are passed for analysis

### ISSUE THREAD

**Issue by alohasiqi** [xihaoli/STAARpipeline-Tutorial#20]
Hello Xihao,

I tried to run both Individual_Analysis() and Sliding_Window() on my aGDS file (178 individuals and 14055 variants on chr22) but the analyses were only performed on 7/NULL variants. I didn't see any other filterings other than "QC_label" in the wrapper methods and the sites are all "PASS" in my case. See below.

I'm not sure if there are additional filterings performed on the backend and most of my sites failed. Can you help figure this out or potentially direct me to these functions so that I may see how they actually worked? Thanks!

A side question is how is STAAR handling imputed SNP dosage if it can?                                        
```
results <- try(Sliding_Window(chr=22,start_loc=start_loc_sub,end_loc=200000,
                                  sliding_window_length=sliding_window_length,type="multiple",
                                  genofile=genofile,obj_nullmodel=obj_nullmodel,Use_annotation_weights=Use_annotation_weights,
                                  QC_label=QC_label,variant_type=variant_type,geno_missing_imputation=geno_missing_imputation,
                                  Annotation_name_catalog=Annotation_name_catalog,
                                  rare_maf_cutoff=1,rv_num_cutoff=0, Annotation_name=Annotation_name))
# of selected samples: 178
# of selected variants: 7
# of selected samples: 178
# of selected variants: 14,055
```
```
results_individual_analysis<-Individual_Analysis(chr=22,start_loc=start_loc,end_loc=20000,
                                                     genofile=genofile,obj_nullmodel=obj_nullmodel,mac_cutoff=20, variant_type=variant_type,
                                                     geno_missing_imputation=geno_missing_imputation)
> results_individual_analysis
NULL
```

**Comment by alohasiqi** [comment]
Hi Xihao,

I checked the manual of STAARpipeline and realized my question about a small number of passed variants might be related to the rare_maf_cutoff in the argument (or may not since I set it to 1).

How was that cutoff calculated? Is it based on the FAVOR annotation from gnomad or calculated from my sample cohorts? 
Does sample size matter for this argument? or for the general analyses (e.g., sliding_window etc), are there any recommended sample sizes or depths? 

Thanks!

**Comment by zilinli1988** [comment]
The rare_maf_cutoff is related to the variants you included in the rare variant association analysis. The default is 0.01, meaning we only have the variant with MAF<0.01 in the rare variant association analysis. The MAF is calculated using your data; for example, when the sample size is 200 and the minor allele account is 10, the MAF=10/200/2=0.025. In your case, the sample size is 178; you might want to set a much larger MAF cutoff than 0.01.

**Comment by alohasiqi** [comment]
Thanks for your explanation. Since I set "rare_maf_cutoff=1,rv_num_cutoff=0" in my sliding window arguments, it presumably didn't remove any variants and considered any variants as rare. What would be other reasons for having a small number of passed variants in this case? Thanks

**Comment by zilinli1988** [comment]
Chromosome 22 is around 50 Mb, and you set the sliding window length as 200 kb in your example. The number of variants is only 14,055 in your data, and we know there are not many variants in the start position of chromosome 22. If you ran the analysis for the whole chromosome 22, we expected several sliding windows that included tens of variants.

**Comment by alohasiqi** [comment]
Thanks for your analyses and that's my expectation as well. I'm testing the exome sequencing data from Illumina so the variant numbers are not that much...I'm thinking of possible reasons for such issue since that didn't seem to be usual.

**Comment by zilinli1988** [comment]
In the case of WES data with a small sample size, you could try to define the windows using the position of genes. For example, the function "Sliding_Window_Single" in STAARpipeline might be helpful.

**Comment by alohasiqi** [comment]
I dont think there is a function called "Sliding_Window_Single" in the current package.

```
library(STAAR)
library(STAARpipeline)
??Sliding_Window_Single
No vignettes or demos or help files found with alias or concept or
title matching ‘Sliding_Window_Single’ using regular expression
matching.
```

**Comment by zilinli1988** [comment]
This is a built-in function in the STAARpipeline package. You could run the analysis using the "Sliding_Window" function by setting the start and end positions. Please take a look at the document for the details. I will close this issue if you do not have any more questions.

**Comment by alohasiqi** [comment]
Ok thanks for working through this issue with me and I appreciate your help! Let's see if I can find any other solutions to this and I may post it here and reach out again.
