### ISSUE TITLE
Running staarpipeline docker image

### ISSUE THREAD

**Issue by pthami07** [xihaoli/STAARpipeline-Tutorial#24]
Hi Xihaoli,
Thanks for this seemingly great tool, I’d like to try it out. I’m having challenges with installing the staarpipeline dependencies. I’ve now pulled the docker image into an HPC as a singularity image. How do I run the image with the Rscripts that you have provided on GitHub?

**Comment by xihaoli** [comment]
Hi @pthami07,

Thanks for your interest in STAARpipeline. For the usage of docker as a singularity image file (sif), below are some example scripts for [Slurm Workload Manager](https://slurm.schedmd.com/quickstart.html):

```
### Example 1: use sif to run an interactive R
salloc -p test -n 1 -t 00-08:00 --mem=6000 singularity shell staarpipeline_0.9.6.sif
R

### Example 2: use sif to run a single R script
salloc -p test -n 1 -t 00-08:00 --mem=6000 singularity shell staarpipeline_0.9.6.sif
R CMD BATCH Association_Analysis_PreStep.r

### Example 3: use sif in batch jobs
sbatch STAARpipeline_Gene_Centric_Coding.sh STAARpipeline_Gene_Centric_Coding.r
```
Note: In [STAARpipeline_Gene_Centric_Coding.sh](https://github.com/xihaoli/STAARpipeline-Tutorial/blob/main/batch%20jobs/STAARpipeline_Gene_Centric_Coding.sh#L18) of Example 3, change `/n/.../Rscript` to `singularity exec staarpipeline_0.9.6.sif Rscript`

Best,
Xihao
