### ISSUE TITLE
run this pipline in crop population

### ISSUE THREAD

**Issue by HaoWangLYL** [xihaoli/STAARpipeline-Tutorial#25]
Dear Xihao Li,
       I want to know whether we could run this pipline in crop population?

**Comment by xihaoli** [comment]
Hi @HaoWangLYL,

Thanks for reaching out. Methodologically, the pipeline can be used for phenotype-genotype association analysis in the crop population. However, in practice, it depends on whether your data format is suitable for the input of the STAARpipeline.

Hope this helps.

Best,
Xihao

**Comment by HaoWangLYL** [comment]
Thank you for your attention&nbsp;


635169288
***@***.***



&nbsp;
