### ISSUE TITLE
STAAR sliding window errors

### ISSUE THREAD

**Issue by Alexei-Lipov** [xihaoli/STAARpipeline-Tutorial#26]
Dear Xihao Li,

I have found your package very useful, and I thank you for your clear and easy to follow pipeline tutorial. 

I would like to ask you about an issue I've encountered. When running the fixed sliding window analysis I get the following odd Manhattan plot:

![sliding_window_manhattan](https://user-images.githubusercontent.com/57069931/230111449-6e2580c9-f5bd-49a9-9959-225bd8b3328c.png)

It seems to tend to "work" at the start of chromosomes and then skip large distances for the rest of each chromosome, resulting in a sparse number of windows evaluated. 

I concomitantly get the following error as well while running the analysis:

`warning: eig_sym(): given matrix is not symmetric
Error : eig_sym(): decomposition failed`

This occurs repeatedly, though the code still seems to progress, outputting ascending integers (presumably indices), e.g. 2, bunch of errors, 3, bunch of errors, etc. See below for an example:

```
[1] 3
# of selected samples: 1,177
# of selected variants: 292

warning: eig_sym(): given matrix is not symmetric
Error : eig_sym(): decomposition failed
Error : eig_sym(): decomposition failed

warning: eig_sym(): given matrix is not symmetric
Error : eig_sym(): decomposition failed

warning: eig_sym(): given matrix is not symmetric
Error : eig_sym(): decomposition failed

warning: eig_sym(): given matrix is not symmetric
Error : eig_sym(): decomposition failed

warning: eig_sym(): given matrix is not symmetric
Error : eig_sym(): decomposition failed

warning: eig_sym(): given matrix is not symmetric
Error : eig_sym(): decomposition failed

warning: eig_sym(): given matrix is not symmetric
Error : eig_sym(): decomposition failed

warning: eig_sym(): given matrix is not symmetric
Error : eig_sym(): decomposition failed

warning: eig_sym(): given matrix is not symmetric
Error : eig_sym(): decomposition failed

warning: eig_sym(): given matrix is not symmetric
Error : eig_sym(): decomposition failed

warning: eig_sym(): given matrix is not symmetric
Error : eig_sym(): decomposition failed

warning: eig_sym(): given matrix is not symmetric
Error : eig_sym(): decomposition failed

warning: eig_sym(): given matrix is not symmetric
Error : eig_sym(): decomposition failed

warning: eig_sym(): given matrix is not symmetric
Error : eig_sym(): decomposition failed

warning: eig_sym(): given matrix is not symmetric
Error : eig_sym(): decomposition failed

warning: eig_sym(): given matrix is not symmetric
Error : eig_sym(): decomposition failed

warning: eig_sym(): given matrix is not symmetric
Error : eig_sym(): decomposition failed

warning: eig_sym(): given matrix is not symmetric
Error : eig_sym(): decomposition failed

warning: eig_sym(): given matrix is not symmetric
Error : eig_sym(): decomposition failed
# of selected samples: 1,177
# of selected variants: 1,007,368
[1] 4
# of selected samples: 1,177
# of selected variants: 243
```

Do you have any idea what the issue might be?

I would be very much grateful for any help you could provide. 

Many thanks,

Alex

**Comment by xihaoli** [comment]
Dear Alex,

Thank you for letting me know. We have yet to encounter this type of error. After a brief investigation, I can confirm that (1) all of the results that you currently have (the p-values in your Manhattan plot) are valid; (2) this is more of a numerical issue, which relatively small sample sizes may cause.

We will take a further investigation and see if anything can be amended to avoid this error.

Best,
Xihao

**Comment by Alexei-Lipov** [comment]
Dear Xihao,

Thank you for replying. I'm working with ~400 cases and ~700 controls, so indeed my sample size is considerably smaller than the example in your paper (~20,000). 

The default setting for the sliding window analysis is a window size of 2 kb and a "rare_MAF_cutoff" of 0.01. To try to circumvent my small sample size issue, I increased this to a window size of 100 kb and a "rare_MAF_cutoff" of 0.05. However, it still doesn't work. 

With 800 alleles in cases, I should be able to detect variants down to a frequency of 0.125%. The rare MAF cutoff is above this, at 5%. In addition, I am accumulating alleles across a window of 100 kb, which is a reasonably large distance. 

So, somehow, I am not able to detect at least two variants less than 5% MAF in the majority of 100 kb window across the genome, using 1100 individuals. 

Also, I'm not sure a low sample size explains why the sliding window works properly only at the start of chromosomes? 

Do you have any suggestions? For instance, what parameters I should choose for the sliding window analysis? Perhaps I should try the dynamic window analysis?

Many thanks for your help,

Alex

**Comment by xihaoli** [comment]
Dear Alex,

Thank you for providing the additional information. Your justifications for using a "rare_MAF_cutoff" of 0.05 and longer sliding windows are reasonable. Yes, please try the dynamic window analysis, and feel free to keep us posted [via email](mailto:xihaoli@g.harvard.edu,li@hsph.harvard.edu) if you have any follow-up questions.

Hope this helps.

Best,
Xihao

**Comment by Alexei-Lipov** [comment]
Thank you, Xihao, for your feedback.
