### ISSUE TITLE
Question about selecting variants to calculate sparse GRM

### ISSUE THREAD

**Issue by ikarus97** [xihaoli/STAARpipeline-Tutorial#3]
Dear authors,

I'm trying to use your pipeline to our association study, but got questions about the way to build GRM.
Is it correct to use the common (MAF > 5%) variants to build GRM, so that we can capture population structure among individuals?
Or should I use the rare variants (those to be used in the main analysis), so we capture the similarity between individuals as will be observed in the main analysis?

Thank you,
In-Hee

**Comment by xihaoli** [comment]
Hi In-Hee,

Thanks for your question. To our knowledge, the standard pipelines to build GRM (e.g. GENESIS and GCTA) are based on KING to infer sample relatedness. KING recommends filtering out rare variants when generating GRM for WGS studies. More details can be found in the [KING Tutorial](https://www.kingrelatedness.com/manual.shtml).

Please feel free to let me know if you have any additional questions.

Best,
Xihao
