### ISSUE TITLE
Number of jobs

### ISSUE THREAD

**Issue by pthami07** [xihaoli/STAARpipeline-Tutorial#31]
Hi Xihao,
I am using a different dataset and have slightly different number of jobs for the following analyses:
sum(jobs_num$individual_analysis_num) = 294 
sum(jobs_num$sliding_window_num) = 574 
sum(jobs_num$scang_num) = 1883 
I'm not sure about how to determine the number of jobs for gene-centric coding and noncoding analyses. Please advise on whether I have to use similar number of jobs as you for gene-centric coding and noncoding analyses.
Thanks.

**Comment by pthami07** [comment]
Hi Xihao,

This helps. Thanks a lot for your timely response.

Best,
Prisca.

**Comment by xihaoli** [comment]
Hi @eliu98,

The number of jobs is an operational parameter representing the number of parallel computing jobs you would submit and run. The number of tests is what you should use to account for multiple comparisons. For example, the Bonferroni-corrected alpha level should be 0.05/number of tests.

Specifically, for sliding window analysis, the row dimension of your output table (which depends on the sliding window length) represents the number of tests. For dynamic window analysis, SCANG can automatically adjust for multiple testing of all the moving windows, including some overlapping windows of different sizes, to control the family-wise/genome-wide error rate (FWER/GWER) at a given significance level (default = 0.05).

Hope this is clear.

Best,
Xihao
