### ISSUE TITLE
Phenofile in STAARpipeline_Null_Model.r

### ISSUE THREAD

**Issue by SheaCheng2000** [xihaoli/STAARpipeline-Tutorial#32]
Hi, 

Thanks for the amazing tool! 
When constructing the null model using STAARpipeline_Null_Model.r, should the sample in 'pheno.csv' be the same as input vcf (which is used in the very beginning and converted to GDS files)? Or the sample in 'pheno.csv' could be a subset of that in input vcf? 

Now I only want to analyze the samples in 'pheno.csv'. When I used STAARpipeline_STAAR2SCANG.r, it reported `Error in y %*% diag(eigen_diff) : non-integral arguments`. So I am wondering if the inconsistency of pheno.csv and input vcf is the reason for the error?

Thanks!
Shea

**Comment by xihaoli** [comment]
Hi Shea,

Thanks for your question. When fitting the null model, the samples in 'pheno.csv' can either be exactly the same as the samples in the input vcf file, or a subset of it. Just need to make sure that there should not be samples that are used in your null model, but not part of the input vcf file.

Hope this helps.

Best,
Xihao

**Comment by SheaCheng2000** [comment]
Hi Xihao,

Thanks for your reply! I checked that the samples in 'pheno.csv'  is indeed a subset of the input vcf samples. Then what could be the possible reason for the error?  `Error in y %*% diag(eigen_diff) : non-integral arguments.`

Regards,
Shea

**Comment by zilinli1988** [comment]
We have never seen this error before. We recommend you run the code of STAAR2SCANG.r line by line to check.

**Comment by SheaCheng2000** [comment]
Hi Zilin,

Thanks for your guidance! I have checked the STAAR2SCANG.r line by line, and identified the potential issue. I fit the null model only use sex as covariate, while my cohort is a female cohort, possibly causing the matrix to be not fully rank? To address this, I replaced the sex with PC1-3 and no errors were encountered thereafter.)

Thanks again for your kind help!

Shea
