### ISSUE TITLE
No Manhattan or QQ plots from STAARpipelineSummary_Dynamic_Window.r?

### ISSUE THREAD

**Issue by kwdoyle** [xihaoli/STAARpipeline-Tutorial#38]
Hello,

While running through the summary scripts, it seems the dynamic window analysis summary does not produce any plots? The README does state that it should...

Within the function `Dynamic_Window_Results_Summary.R` in the STAARpipelineSummary repo, should the results from each separate SCANG table within `SCANG_res` be plotted?

**Comment by xihaoli** [comment]
Hi @kwdoyle, you are correct. The dynamic window analysis does not produce plots, as the manhattan/QQ plots do not apply to dynamic window analysis.
