### ISSUE TITLE
Ancestry PCs / kinship

### ISSUE THREAD

**Issue by kwdoyle** [xihaoli/STAARpipeline-Tutorial#39]
This is more of a question than an issue regarding including ancestry information in the model.

I see there is the step of generating the GRM to pass to the null model function using the `kins` argument. When defining the model, however, the example code in `STAARpipeline_Null_Model.r` also includes 10 principal components as covariates. Are these also the ancestry components? If so, would they be accounted for twice then when also supplying the GRM?

I've generated the null model with including ancestry PCs as covariates and excluded the GRM (i.e., setting `kins=NULL`). After running the analyses, I'm seeing some genomic deflation in my QQ plots, especially in the gene-centric noncoding analysis. I'm wondering if my setup could be the issue?

**Comment by xihaoli** [comment]
Hi @kwdoyle,

Thanks for your question. If you use [FastSparseGRM](https://github.com/rounakdey/FastSparseGRM) to create the sparse GRM, it will capture the unaccounted population structure by ancestry PC and family relatedness. That is, the ancestry components will be accounted for twice.

If your data exhibits sample relatedness while you exclude the GRM, then your QQ plot could go either way. On another note, if you are interested in a continuous trait, one typically performs rank-based inverse normal transformation, before fitting the null mode.

Hope this clarifies your question.

Best,
Xihao

**Comment by kwdoyle** [comment]
Thanks for your response, @xihaoli 

I realized this deflation issue was due to something entirely else, but now I'm experiencing an _inflation_ issue.

I originally ran the pipeline, adding 10 PCs as covariates and leaving out the GRM (setting kins=NULL), using a European-only cohort and encountered no inflation. When I increase my sample size to include other ancestries, however, I now see a fair amount of inflation.

As a test, I ran the multi-ancestry cohort again _excluding_ the PCs as covariates and saw the inflation was much worse. It seems including the PCs just as covariates is doing _something_ to adjust for population structure, but apparently not enough.

I am still uncertain if I should include the GRM along with the PCs as covariates in the null model. Should the ancestry components be accounted for twice?

**Comment by xihaoli** [comment]
Hi @kwdoyle,

Thanks for your message. A brief answer is yes, you should also include the GRM along with the PCs as covariates in the null model. If you are using [FastSparseGRM](https://github.com/rounakdey/FastSparseGRM), then it can efficiently calculate genetic PCs and the **ancestry-adjusted** sparse GRM, such that the ancestry components are not accounted for twice.

Best,
Xihao

**Comment by kwdoyle** [comment]
@xihaoli ok, great. One other question: I am working with a cohort from TOPMed that was previously pruned for unrelated samples. Is this GRM meant to handle overall population structure or is it mainly to handle truly related samples.

I'm fairly sure the inflation issue I'm seeing is due to ancestry, but I'm unsure how much including the GRM will help, seeing as these samples are already supposed to be unrelated.

**Comment by xihaoli** [comment]
Hi @kwdoyle,

Glad to hear you are using TOPMed. Is your phenotype continuous or dichotomous? If continuous, did you use a heteroskedastic linear mixed model (HLMM) to account for ancestry-specific residual variance (this is enabled by the `group` parameter in the null model fitting)? Also, did you perform a rank-based inverse normal transformation on each of the ancestry subgroups, before fitting the null model?

Thanks,
Xihao

**Comment by kwdoyle** [comment]
@xihaoli No, I am using a dichotomous outcome, so I assumed both of these would not be applicable...

**Comment by kwdoyle** [comment]
@xihaoli I will try using a linear mixed model and setting the ancestry group for the `group` argument. To do this, it seems I also need to supply the GRM--is that correct? If I attempt to run fit_nullmodel this way with kins=NULL, I get an error of
```
Error in glmmkin(fixed = fixed, data = data, kins = kins, id = id, random.slope = random.slope,  :
  Error: heteroscedastic linear models for unrelated observations have not been implemented.
```

Poking around in the source code of `glmmkin` seems to confirm this...

**Comment by xihaoli** [comment]
Hi @kwdoyle,

From a statistical perspective, it would not be ideal to model binary traits using (heteroskedastic) linear (mixed) models. You should still use logistic (mixed) models to model binary traits to control for genomic inflation/deflation.

Best,
Xihao

**Comment by kwdoyle** [comment]
Hi @xihaoli,

Would it even be possible to fix a logistic mixed effect model using `fit_nullmodel`? This would clearly be the ideal choice as clearly, yes, it doesn't make sense to treat my dichotomous outcome variable as continuous using the linear mixed effect model.

However, `glmmkin` only seems to accept heteroscedastic linear mixed models. There doesn't seem to be a way to account for any group mixed effect if you want to model a dichotomous variable.

Would I need to forgo the use of `fit_nullmodel` and create my own null model externally?

**Comment by xihaoli** [comment]
Hi @kwdoyle,

I would like to clarify that it is enabled to fit a logistic mixed effect model using `fit_nullmodel` by using `family = binomial(link = "logit")`. Note that for a dichotomous variable, you don't have heteroscedastic error terms due to the mean-variance relationship. So if you want to allow for group-specific effects, you could model them in the mean model by including certain fixed-effect terms. At the same time, `fit_nullmodel` allows for including sparse GRM by specifying `kins`, so that logistic mixed model will be fit.

Hope this is clear.

Best,
Xihao

**Comment by rounakdey** [comment]
Hi @kwdoyle, just wanted to chime in and clarify some details on the use of the sparse GRM. The sparse GRM is meant to adjust for the relatedness only, and the PCs are meant to adjust for the ancestry only. If you truly only have unrelated subjects in your dataset, then the GRM will not be of any help for you. However, that will depend on how you have pruned the related subjects, how accurate the pruning procedure was. I would advice to run `king --ibdseg --degree 4` on the dataset to see whether the pruning was accurate.
I would focus on how you have calculated the PCs, and how good the PCs are to represent the ancestry. A quick way to check will be to see if the PC1 vs PC2 (and/or later PCs) plots show differentiation among the different ancestral backgrounds you have in the data.
