### ISSUE TITLE
Dynamic_Window_SCANG error(s)

### ISSUE THREAD

**Issue by lj1257111** [xihaoli/STAARpipeline-Tutorial#40]
Hello, I have been receiving two errors. 

Error 1 occurs when "res" (a SCANG output) all equal zero, or not applicable, the pipeline breaks before moving to next sub_seq_num. 
This is usually fixed by increasing the rare_maf_cutoff value.

Error 2 I am not sure what is going on: 
`Error in resmost_SCANG_O[1, 3] - resmost_SCANG_O[1, 2] : 
  non-numeric argument to binary operator
Calls: Dynamic_Window_SCANG -> matrix
Execution halted`

Appreciate any help!
Thanks
lj

**Comment by zilinli1988** [comment]
What is your sample size?

**Comment by lj1257111** [comment]
100 samples

**Comment by zilinli1988** [comment]
SCANG is designed for moderate or large samples. When applying it to small samples, you should set the MAF cutoff at least 0.1.
