### ISSUE TITLE
Gene Centric Coding Annotation fails

### ISSUE THREAD

**Issue by kwdoyle** [xihaoli/STAARpipeline-Tutorial#41]
Hello,

When running the script `STAARpipelineSummary_Gene_Centric_Coding_Annotation.r`, I am encountering this error:

```
Error in seqGetData(genofile, paste0(Annotation_dir, Annotation_name_catalog$dir[which(Annotation_name_catalog$name ==  :
  The GDS node "annotation/info/FunctionalAnnotation/rsid" does not exist.
Calls: Gene_Centric_Coding_Info -> info_plof -> seqGetData
```

The rsids for each variant are not included when annotating the gds files in the earlier steps. Are the rsids supposed to be within the FAVOR database files? I'm using the csv files downloaded from the FAVOR database website and the rsids don't seem to be in there..

**Comment by xihaoli** [comment]
Hi @kwdoyle,

Thanks for asking. I can confirm that `rsID` is part of the [FAVOR Essential Database](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/1VGTJI). Could you please double check whether your aGDS files based on FAVOR Full Database include `rsID` as a field? If not, you may exclude `rs_num` from `Annotation_name` in `STAARpipelineSummary_Gene_Centric_Coding_Annotation.r`.

Hope this is clear.

Best,
Xihao

**Comment by xihaoli** [comment]
Hi @kwdoyle, I'd like to check whether this issue has been resolved. If so, please feel free to close it. Thanks!
