### ISSUE TITLE
Known_Loci_Pruning error

### ISSUE THREAD

**Issue by jingling000** [xihaoli/STAARpipeline-Tutorial#46]
When I execute the script STAARpipelineSummary_Known_Loci_Pruning.r, there are several chromosomes that did not generate corresponding data, and the error is as follows:
         used (Mb) gc trigger (Mb) max used (Mb)
Ncells 283209 15.2     664320 35.5   450929 24.1
Vcells 487090  3.8    8388608 64.0  1815701 13.9
[1] 8
# of selected samples: 3,508
# of selected variants: 2
# of selected samples: 3,508
# of selected variants: 2
# of selected samples: 3,508
# of selected variants: 4,303,007
# of selected samples: 3,508
# of selected variants: 1
# of selected samples: 3,508
# of selected variants: 4,303,007
# of selected samples: 3,508
# of selected variants: 2
Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) : 
  没有(非NA)案例可用
Calls: LD_pruning -> Individual_Analysis_cond -> lm -> lm.fit
停止执行
Is the reason for this that the provided known pathogenic loci do not exist in my data? If so, how can I avoid conflicts between removing certain regions during QC and this step?

Thank you for your help.

**Comment by xihaoli** [comment]
Hi @jingling000,

Thank you for the question. I have been checking what could be the reason that caused this issue, and I recently updated the [LD_pruning function](https://github.com/xihaoli/STAARpipeline/commit/b6a9cf35450470f7e0a38dec2654462cb3d1932a), which may be relevant. Could you please install the latest version of the STAARpipeline package and try it again?

Best,
Xihao

**Comment by jingling000** [comment]
Hi Xihao,
Thank you very much for your help. I have resolved my issue.
Best,
Jingling
