### ISSUE TITLE
vcf to gds

### ISSUE THREAD

**Issue by wangshuang2024** [xihaoli/STAARpipeline-Tutorial#47]
Hello, @xihaoli. 
In the script of "Varinfo_gds.R" and "gds2agds.R", it has two gds name.  
gds_file_name_1 <- "freeze.5.chr"
gds_file_name_2 <- ".pass_and_fail.gtonly.minDP0.gds"

I wonder what the two documents represent and how they are produced? Thank you.

**Comment by xihaoli** [comment]
Hi @wangshuang2024,

Thanks for reaching out. The `gds_file_name_1` and `gds_file_name_2` are both part of the target gds file name, separated by the `chr` number. For example, if the target gds file is for chromosome 1, and
```
gds_file_name_1 <- "freeze.5.chr"
gds_file_name_2 <- ".pass_and_fail.gtonly.minDP0.gds"
```
then after string concatenation, the target GDS file should have name `freeze.5.chr1.pass_and_fail.gtonly.minDP0.gds`.

Hope this helps.

Best,
Xihao

**Comment by wangshuang2024** [comment]
> Hi @wangshuang2024,
> 
> Thanks for reaching out. The `gds_file_name_1` and `gds_file_name_2` are both part of the target gds file name, separated by the `chr` number. For example, if the target gds file is for chromosome 1, and
> 
> ```
> gds_file_name_1 <- "freeze.5.chr"
> gds_file_name_2 <- ".pass_and_fail.gtonly.minDP0.gds"
> ```
> 
> then after string concatenation, the target GDS file should have name `freeze.5.chr1.pass_and_fail.gtonly.minDP0.gds`.
> 
> Hope this helps.
> 
> Best, Xihao

Thank you. I got it. But I have another question.
my gds file named like chr1.gds. Then, I changed gds_file_name_1 <- "chr"; gds_file_name_2 <- ".gds"  
#           Input
##########################################################################

### DB split information 
file_DBsplit <- "/Rscript/staarpipeline/FAVORdatabase_chrsplit.csv"
### Targeted GDS
dir_geno <- "/202402staarpipeline/gds/"
gds_file_name_1 <- "chr"
gds_file_name_2 <- ".gds"
### output
output_path <- "/202402staarpipeline/output/varinfo_gds/"

chr <- as.numeric(commandArgs(TRUE)[1])

##########################################
Then I used "
Rscript /Rscript/staarpipeline/Varinfo_gds.R >Varinfo_gds.Rout" to run this step.

I got an error.
####
Error in openfn.gds(gds.fn, readonly = readonly, allow.fork = TRUE, allow.duplicate = allow.duplicate) : 
  Can not open file '/202402staarpipeline/gds/chrNA.gds'. No such file or directory
Calls: seqOpen -> openfn.gds
Execution halted
#####

Could you tell me how to solve this problem? Thank you

**Comment by wangshuang2024** [comment]
Hello, @xihaoli . I got another problem and hope you can help me.
In step 2 Annotate the variants. 
for i in 'seq 1 22'; do Rscript /Rscript/staarpipeline/Annotate.R ${i}; done
After I run this code. I got an error.
-----------------
Warning message: 
NAs introduced by coercion 
Error in 1:chr_splitnum : NA/NaN argument
Execution halted 
-----------------
How can I solve this?

**Comment by xihaoli** [comment]
Hi @wangshuang2024,

It seems like your `chr_splitnum` in [line 33 of Annotate.R](https://github.com/xihaoli/STAARpipeline-Tutorial/blob/main/FAVORannotator_csv/Annotate.R#L33) is `NA`. Can you make sure whether the path of your `file_DBsplit` is set correctly? You may perform a manual check by setting `chr <- 1` in [line 24 of Annotate.R](https://github.com/xihaoli/STAARpipeline-Tutorial/blob/main/FAVORannotator_csv/Annotate.R#L24)).

Thanks,
Xihao

**Comment by wangshuang2024** [comment]
> Hi @wangshuang2024,
> 
> It seems like your `chr_splitnum` in [line 33 of Annotate.R](https://github.com/xihaoli/STAARpipeline-Tutorial/blob/main/FAVORannotator_csv/Annotate.R#L33) is `NA`. Can you make sure whether the path of your `file_DBsplit` is set correctly? You may perform a manual check by setting `chr <- 1` in [line 24 of Annotate.R](https://github.com/xihaoli/STAARpipeline-Tutorial/blob/main/FAVORannotator_csv/Annotate.R#L24)).
> 
> Thanks, Xihao

>Thank you , I figure out this problem.  There is another error. 

         used (Mb) gc trigger (Mb) max used (Mb)
Ncells 269061 14.4     654582   35   444042 23.8
Vcells 448538  3.5    8388608   64  1771786 13.6
[1] 1
No such file or directory (os error 2)
[1] 2
No such file or directory (os error 2)
[1] 3
No such file or directory (os error 2)
Selector index 1 is out of bounds. Index must be >= 1 and <= 0.


>I check the path of "file_DBsplit","DB_path“，”xsv” and "output_path", they are all correct.
>DB name like this "/reference/FAVOR/essentialDB/chr1.tar.gz"

**Comment by xihaoli** [comment]
Hi @wangshuang2024,

You would need to first uncompress the `chr1.tar.gz` file before running [Annotate.R](https://github.com/xihaoli/STAARpipeline-Tutorial/blob/main/FAVORannotator_csv/Annotate.R).

Best,
Xihao

**Comment by wangshuang2024** [comment]
> Hi @wangshuang2024,
> 
> You would need to first uncompress the `chr1.tar.gz` file before running [Annotate.R](https://github.com/xihaoli/STAARpipeline-Tutorial/blob/main/FAVORannotator_csv/Annotate.R).
> 
> Best, Xihao

Thank you, Xihao. I solve these problems.
