### ISSUE TITLE
Error in results_plof_genome[, "cMAC"] : subscript out of bounds

### ISSUE THREAD

**Issue by GACGAMA** [xihaoli/STAARpipeline-Tutorial#52]
Hello Xihaoli

When using STAARpipelineSummary_Gene_Centric_Coding.r, I get the following error from Gene_Centric_Coding_Results_Summary:

```
[1] 1
...
[1] 91000
[1] 92000
Error in results_plof_genome[, "cMAC"] : subscript out of bounds
```

I tried different p-values without avail but I'm not sure what this errors means in this context

**Comment by xihaoli** [comment]
Hi @GACGAMA,

I think you are using `STAARpipelineSummary` package `v0.9.7` to summarize the results but using `STAARpipeline` package `v0.9.6` to run the analysis (which did not output `cMAC`). Could you please check?

Best,
Xihao

**Comment by GACGAMA** [comment]
Updating the STAARpipelineSummary to 0.9.7 and the recreating outputs did work!
