### ISSUE TITLE
Followup Question to Issue #28

### ISSUE THREAD

**Issue by samreenzafer** [xihaoli/STAARpipeline-Tutorial#53]
Just to followup on this #28 if we don't have any known loci for our trait, do we set the input variable to `NULL` or should I provide an empty `CSV` file with only a header but no variants. ?

I tried with "NULL" and the script runs, but I'm still wondering if this is the correct way to run the script. 

Thank You.

**Comment by xihaoli** [comment]
Hi @samreenzafer,

Yes, this is correct. If there is no known loci for your trait, then you can set `known_loci <- NULL`. In this case, the conditional analysis p-value should be outputted the same as the unconditional analysis p-value.

Best,
Xihao

**Comment by samreenzafer** [comment]
Thank you for confirming!!
