### ISSUE TITLE
Can't annotate individual variant results

### ISSUE THREAD

**Issue by GACGAMA** [xihaoli/STAARpipeline-Tutorial#56]
Hello Xihao!
The results from individual analysis are outputted as such:

CHR POS REF ALT etc...

I'm trying to annotate these results using common tools to explore (such as VEP)
But the problem is:
Deletions are annotated as:
```
CHR POS REF ALT
1	943528	T	*

```
And insertions:
```
CHR POS REF ALT
1	977780	AAT	ACCAT

```
The problem:
I can't seem to find a version o vcf in which insertions are annotated with the full insertion and deletions are annotated with * on ALT. Only versions of vcf which annotates insertions as . in the REF and deletions with . in the ALT

VEP can't keep with this way of annotating, which makes me lose my deletions when annotating.

Example of VEP output:
`WARNING: Line 815 skipped (1 77568473 A . 0.3299508 0.3299508 2767 0.0003...): Invalid allele string ./0.3299508 or possible parsing error`

Do you have any suggestions?
Could STAAR output a VCF formatted result as summary?

**Comment by xihaoli** [comment]
Hi @GACGAMA,

Thanks for reaching out. Sure, we plan to include this feature of STAAR in the to-do list hopefully soon. In the meantime, please feel free to prepare your data with your ideal input format in the VCF/aGDS file before running STAARpipeline. For individual variant analysis, such variant identification information (CHR-POS-REF-ALT) would not affect your analysis results.

Let me know if you have any questions.

Best,
Xihao

**Comment by GACGAMA** [comment]
Thanks Xihao!
