### ISSUE TITLE
Ukbiobank Agds files generation

### ISSUE THREAD

**Issue by akhilpampana** [xihaoli/STAARpipeline-Tutorial#59]
Hello, 

I am trying to implement staarpipeline in ukbiobank and noticed that the tool was already implemented in the platform of DNAnexus. So Would like to ask if there is a tutorial of how to run it in Dnanexus. Also is there any availability of agds files generated already in ukbiobank while working on the implementation of this tutorial in ukbiobank? If so how to access those files?

Regards
Akhil

**Comment by xihaoli** [comment]
Hi Ahkil,

Thanks for reaching out. Yes, you are right. [STAARpipeline](https://github.com/li-lab-genetics/staarpipeline-rap) has been implemented in DNAnexus as a series of apps, and the app manual is [here](https://tinyurl.com/staarpipelineapps). The only thing users need to perform is to generate a copy of the aGDS files, where one can convert from either [PLINK](https://www.bioconductor.org/packages/release/bioc/manuals/SeqArray/man/SeqArray.pdf#page=14), [VCF](https://www.bioconductor.org/packages/release/bioc/manuals/SeqArray/man/SeqArray.pdf#page=70) or [BGEN](https://github.com/zhengxwen/gds2bgen) directly to GDS, and then annotate it to aGDS using the [FAVORannotator](https://github.com/li-lab-genetics/favorannotator-rap) app.

Let me know if you have any questions.

Best,
Xihao

**Comment by akhilpampana** [comment]
Whats the computation time for converting imputed bgen files to gds files as per your experience?

**Comment by xihaoli** [comment]
Hi @akhilpampana,

The computation time would depend on the data you are working with but should generally be modest. Since you want to run it on DNAnexus, are you working on the [WES interim 450k release](https://biobank.ndph.ox.ac.uk/ukb/field.cgi?id=23150), [WES final release](https://biobank.ndph.ox.ac.uk/ukb/field.cgi?id=23159), or [WGS interim 200k release](https://biobank.ndph.ox.ac.uk/ukb/field.cgi?id=24306)?

Best,
Xihao

**Comment by akhilpampana** [comment]
Hello Xihao,

I am planning to run it on a topmed imputed dataset which I have run gwas based on. Will it take more time of less? sample size is 49k individuals and imputed dataset.

Regards
Akhil 
Akhil

**Comment by xihaoli** [comment]
Hi @akhilpampana,

I think the computational time will be less. You may check the number of genetic variants in your imputed dataset.

Best,
Xihao

**Comment by akhilpampana** [comment]
Thank you so much. I will look into it. Also, I would like to ask how you ran these in dnanexus is it through ttyd or batch job submission?

Regards
Akhil

**Comment by jwilliams10** [comment]
Hi @akhilpampana, I work with Xihao and have experience with running the STAARPipeline through ttyd. Following the app manual that Xihao shared previously, the recursive for loop; 

for CHR in {1..22}; do
dx run staarpipeline --priority=low \
-inullobj_file=${nullmodel} \
-iagds_file=cdbg:/Genotypes/freeze.8/DP0/AGDS_uncompressed/freeze.8.chr${CHR}.pass_and_fail.gtonly.minDP0.gds \
-iannotation_name_catalog_file=cdbg_lipids_staartopmed:/TOPMed_lipids_F8_staarpipeline/Annotation_name_catalog.csv \
-itest_type=Gene_Centric_Coding \
-iuser_cores=40 \
-ioutfile=LDL_F8_gene_centric_coding_chr${CHR} \
-iannotation_dir=annotation/info/FunctionalAnnotation \
--destination=${path} --instance-type="mem3_ssd1_v2_x48" --yes
done

submits 22 jobs that will run independently of each other similar to a batch job submission. I typically start a ttyd session, run the forementioned script which performs gene centric coding analysis for each chromosome, and then close my ttyd session. ttyd is only used as a linux interface to submit jobs, after jobs are submitted the ttyd session retains no value. I have found that linux for loops submitted on ttyd are the easiest and most intuitive way to submit jobs on DNAnexus.

**Comment by akhilpampana** [comment]
hey @jwilliams10 can this be done for bgen to gds conversion too as bash submissions?

**Comment by jwilliams10** [comment]
@akhilpampana I have not done this conversion so I am not entirely sure what it entails. But the vcf to gds conversion is done in R using the SeqArray function. To do this conversion in DNAnexus, the easiest thing would be to use the Swiss Army Knife app. This is essentially a blank virtual machine with some basic programs that can be called in a similar manner to the staarpipeline DNAnexus app. An example call for this would be something like:

dx run app-swiss-army-knife -iin=file.R -icmd="RScript file.R" -y --destination out --instance-type mem1_ssd1_v2_x36

**Comment by akhilpampana** [comment]
Thank you so much for the help. I have tested a code in server and it worked out well and planning to implement in dnanexus

**Comment by xihaoli** [comment]
Thanks @jwilliams10 for your help, and thanks @akhilpampana for confirming it works. Please feel free to close this case and reopen it later if you have any questions in the future.

**Comment by akhilpampana** [comment]
Hello @jwilliams10 quick question, how have to dealt with sparse matrix generation for a sample size of 50k individuals with 250k high-quality variants? I am having memory issues while trying to run king to matrix conversion after running king using genesis in r?

**Comment by xihaoli** [comment]
Hi @akhilpampana,

Have you tried [FastSparseGRM](https://github.com/rounakdey/FastSparseGRM), which generates a sparse GRM directly without converting from a dense one? My experience with using FastSparseGRM is that it is memory-efficient. If you have any questions, please feel free to let me or @rounakdey know.

Best,
Xihao
