### ISSUE TITLE
Plots for gene centric ncRNA regions

### ISSUE THREAD

**Issue by samreenzafer** [xihaoli/STAARpipeline-Tutorial#60]
Hi.
I would like to also get the plots for the gene centric noncoding ncRNA regions. 
I see that the default (NULL) would be used for `ncRNA_pos` in the `STAARpipeline-Tutorial/STAARpipelineSummary_Gene_Centric_Noncoding.r`  script, since no value is provided. 

 @param ncRNA_pos positions of ncRNA genes, required for generating the Manhattan plot and Q-Q plot of the results of ncRNA genes (default=NULL).

Can you please tell me what type of data structure I should provide to this argument so that I can make the script print the respective plots? I do already have the `ncRNA_sig.csv` file with 10 lines, and these lines are also included in the `noncoding_sig.csv` summary file.

**Comment by xihaoli** [comment]
Hi @samreenzafer,

Thanks for your patience. We have updated the [`STAARpipelineSummary`](https://github.com/xihaoli/STAARpipelineSummary) package to include an R object of `ncRNA_pos`. Please update the `STAARpipelineSummary` to its latest version, and when you `library(STAARpipelineSummary)`, `ncRNA_pos` will be automatically loaded in the environment and can be used for ncRNA plotting.

I have also updated the `STAARpipeline-Tutorial/STAARpipelineSummary_Gene_Centric_Noncoding.r` script to reflect the change as well.

Best,
Xihao

**Comment by jingydz** [comment]
What does the "ncRNA_pos" refer to in the STAARpipelineSummary_Gene_Centric_Noncoding.r script? 

Hello, I have utilized your most recent script (https://github.com/xihaoli/STAARpipeline-Tutorial/blob/main/STAARpipelineSummary_Gene_Centric_Noncoding.r) from the link provided, and I haven't included an additional definition for ncRNA_pos. Furthermore, I have just installed the STAARpipelineSummary package today, so it should be up to date. 

Yet, I am still met with an error: 
'Error: object 'ncRNA_pos' not found.' 
To provide more context, my Gene_Centric_Noncoding/noncoding_sig.csv file includes 107 significant genes. 
I attempted to set ncRNA_pos manually with the format ncRNA_pos="chr:start-end", but encountered another error: 
[1] "Manhattan plot", 
Error in UseMethod("left_join"): 
no applicable method for 'left_join' applied to an object of class "character"'
'Calls: Gene_Centric_Noncoding_Results_Summary -> <Anonymous>', 
after which the execution stopped. 

Should I eliminate all references to ncRNA_pos, such as altering the last line of the script from 
alpha=alpha, ncRNA_pos=ncRNA_pos, manhattan_plot=TRUE, QQ_plot=TRUE to 
alpha=alpha, manhattan_plot=TRUE, QQ_plot=TRUE? Is this approach viable?

**Comment by xihaoli** [comment]
Hi @jingydz, when you `library(STAARpipelineSummary)`, does `ncRNA_pos` automatically loaded to your environment?

**Comment by xihaoli** [comment]
Hi @jingydz, thank you for confirming the `ncRNA_pos` can be successfully loaded and ncRNA plots can be made under the new `STAARpipelineSummary` package.

@samreenzafer I'll close this issue for now. Feel free to ask additional questions if you have.
