### ISSUE TITLE
FATAL ERROR - Too many first alleles as the major allele (~21.5%).

### ISSUE THREAD

**Issue by jingydz** [xihaoli/STAARpipeline-Tutorial#61]
Start time is 2024/06/12--12:53
KING 2.2 - (c) 2010-2019 Wei-Min Chen

The following parameters are in effect:
                   Binary File : /xxx/rare_variant/GRM/chrall.2082.mac1.filt.mind.geno.maf.bed (-bname)

Additional Options
         Close Relative Inference : --related, --duplicate
   Pairwise Relatedness Inference : --kinship, --ibdseg [ON], --ibs, --homog
              Inference Parameter : --degree [4]
         Relationship Application : --unrelated, --cluster, --build
                        QC Report : --bysample, --bySNP, --roh, --autoQC
                     QC Parameter : --callrateN, --callrateM
             Population Structure : --pca, --mds
              Structure Parameter : --projection
              Disease Association : --tdt
   Quantitative Trait Association : --mtscore
                Association Model : --trait [], --covariate []
            Association Parameter : --invnorm, --maxP
               Genetic Risk Score : --risk, --model [], --prevalence, --noflip
              Computing Parameter : --cpus [10]
                   Optional Input : --fam [], --bim [], --sexchr [23]
                           Output :
                                    --prefix [/xxx/rare_variant/GRM/KING.PCa],
                                    --rplot

KING starts at Wed Jun 12 12:53:24 2024
Loading genotype data in PLINK binary format...
Read in PLINK fam file /xxx/rare_variant/GRM/chrall.2082.mac1.filt.mind.geno.maf.fam...
  PLINK pedigrees loaded: 2071 samples
Read in PLINK bim file /xxx/rare_variant/GRM/chrall.2082.mac1.filt.mind.geno.maf.bim...
  Genotype data consist of 5593621 autosome SNPs
  PLINK maps loaded: 5593621 SNPs
Read in PLINK bed file /xxx/rare_variant/GRM/chrall.2082.mac1.filt.mind.geno.maf.bed...
0%^M6%^M13%^M19%^M25%^M31%^M38%^M44%^M50%^M56%^M63%^M69%^M75%^M81%^M88%^M  PLINK binary genotypes loaded.
94%^M  KING format genotype data successfully converted.

Options in effect:
        --ibdseg
        --degree 4
        --cpus 10
        --prefix /xxx/rare_variant/GRM/KING.PCa

FATAL ERROR -

Too many first alleles as the major allele (~21.5%). Please use plink1.9 --make-bed to regenerate the genotype data again.

Finish time is 2024/06/12--12:54

In the FastSparseGRM pipeline, I met this error.

But I indeed used the plink1.9 (PLINK v1.90b6.9 64-bit (4 Mar 2019)) to generate the genotype, why it run unsuccessfully?

**Comment by xihaoli** [comment]
Hi @jingydz,

Thanks for letting me know. This issue could be more related to [KING](https://www.kingrelatedness.com/index.shtml) or [FastSparseGRM](https://github.com/rounakdey/FastSparseGRM/). Please create an issue [here](https://github.com/rounakdey/FastSparseGRM/issues) and redirect this issue.
