### ISSUE TITLE
warning messages in generating the annotated GDS (aGDS) file.

### ISSUE THREAD

**Issue by jingydz** [xihaoli/STAARpipeline-Tutorial#62]
used (Mb) gc trigger (Mb) max used (Mb)
Ncells 283209 15.2     664320 35.5   450929 24.1
Vcells 487102  3.8    8388608 64.0  1815714 13.9
[1] 624684     22
Warning messages:
1: In add.gdsn(ans, nm[i], val[[i]], compress = compress, closezip = closezip,  :
  Missing characters are converted to "".
2: In add.gdsn(ans, nm[i], val[[i]], compress = compress, closezip = closezip,  :
  Missing characters are converted to "".
3: In add.gdsn(ans, nm[i], val[[i]], compress = compress, closezip = closezip,  :
  Missing characters are converted to "".
4: In add.gdsn(ans, nm[i], val[[i]], compress = compress, closezip = closezip,  :
  Missing characters are converted to "".
5: In add.gdsn(ans, nm[i], val[[i]], compress = compress, closezip = closezip,  :
  Missing characters are converted to "".
6: In add.gdsn(ans, nm[i], val[[i]], compress = compress, closezip = closezip,  :
  Missing characters are converted to "".
7: In add.gdsn(ans, nm[i], val[[i]], compress = compress, closezip = closezip,  :
  Missing characters are converted to "".
8: In add.gdsn(ans, nm[i], val[[i]], compress = compress, closezip = closezip,  :
  Missing characters are converted to "".
9: In add.gdsn(ans, nm[i], val[[i]], compress = compress, closezip = closezip,  :
  Missing characters are converted to "".

 load("/xxx/rare_variant/association/pre_step/jobs_num.Rdata")
 ls()
 [1] "jobs_num"
 jobs_num
    1.    chr start_loc end_loc individual_analysis_num sliding_window_num scang_num
    2. 1    1        NA      NA                      NA                 NA        NA
    3. 2    2        NA      NA                      NA                 NA        NA
    4. 3    3        NA      NA                      NA                 NA        NA
    5. 4    4        NA      NA                      NA                 NA        NA
    6. 5    5        NA      NA                      NA                 NA        NA
    7. 6    6        NA      NA                      NA                 NA        NA
    8. 7    7        NA      NA                      NA                 NA        NA
    9. 8    8        NA      NA                      NA                 NA        NA
    10. 9    9        NA      NA                      NA                 NA        NA
    11. 10  10        NA      NA                      NA                 NA        NA
    12. 11  11        NA      NA                      NA                 NA        NA
    13. 12  12        NA      NA                      NA                 NA        NA
    14. 13  13        NA      NA                      NA                 NA        NA
    15. 14  14        NA      NA                      NA                 NA        NA
    16. 15  15        NA      NA                      NA                 NA        NA
    17. 16  16        NA      NA                      NA                 NA        NA
    18. 17  17        NA      NA                      NA                 NA        NA
    19. 18  18        NA      NA                      NA                 NA        NA
    20. 19  19        NA      NA                      NA                 NA        NA
    21. 20  20        NA      NA                      NA                 NA        NA
    22. 21  21        NA      NA                      NA                 NA        NA
    23. 22  22        NA      NA                      NA                 NA        NA

**Comment by xihaoli** [comment]
Hi @jingydz,

These warning messages indicate that some of the missing characters in the annotation database will be converted to an empty string `""` when integrating into the aGDS file, so they are not errors.

It seems like your `jobs_num` object is empty, which is unexpected. What did you use in your `Association_Analysis_PreStep.r`?

Best,
Xihao

**Comment by jingydz** [comment]
My apologies for the delayed response.
I've already resolved the issue. It was because I used the additional script you provided to change the path of QC_label to "annotation/info/QC_label".

**Comment by xihaoli** [comment]
No problem. Thanks for the updates!
