### ISSUE TITLE
kinship matrix

### ISSUE THREAD

**Issue by eliu98** [xihaoli/STAARpipeline-Tutorial#64]
Hi,

I am wondering if I could account for the relatedness by providing a kinship matrix in the null model? If so, how does it work? Do I still need the GRM? 

Thank you!
Elaine

**Comment by xihaoli** [comment]
Hi @eliu98,

Yes, you could account for the relatedness by providing a kinship matrix in the null model. Specifically, if pedigree information is available, then Φ is a pedigree-based kinship matrix. However, in practice, pedigree information is often unavailable or incomplete. In this case, Φ can be estimated by a (sparse) genetic relatedness matrix, for example, using [FastSparseGRM](https://github.com/rounakdey/FastSparseGRM).

Best,
Xihao

**Comment by eliu98** [comment]
Thank you!
