### ISSUE TITLE
What is the difference between the "results_temp" and "results_m" results?

### ISSUE THREAD

**Issue by jingydz** [xihaoli/STAARpipeline-Tutorial#68]
When summarizing the results of the coding region, what is the difference between the "results_temp" and "results_m" results?

**Comment by yuxinyuanqt** [comment]
Hi @jingydz 

Are you referring to the variables within the _Gene_Centric_Coding_Results_Summary_ function? If so, I only found the "results_m" variable in the _Gene_Centric_Coding_Results_Summary_ function. The "results_m" variable serves as an intermediate storage for results. For example, when generating a Manhattan plot, "results_m" is a data frame that holds the p-values for various functional categories of genes.

Hope this helps.

Best,
Yuxin

**Comment by xihaoli** [comment]
Hi @jingydz,

Has your issue been resolved by @yuxinyuanqt?

Edit of 12/6/24: I'll close this case. Please reopen if you have any additional questions.

Thanks,
Xihao
