### ISSUE TITLE
Question regarding functional annotation scores

### ISSUE THREAD

**Issue by liangshy3** [xihaoli/STAARpipeline-Tutorial#72]
Hello Dr. Li,

I have a question regarding the functional annotation scores in FAVOR. I noticed that the original values are used in STAARpipeline (e.g., ,linsight). In the tutorial of STAAR, the website says "In practice, the Phred score is calculated based on all variants across the genome (http://favor.genohub.org/)". I thought these two packages are similar and now I'm confused. Should I calculate rank of functional annotations for all variants in FAVOR? Or the rank can be calculated for variants in our dataset only instead of going through billions of scores in FAVOR?

Many thanks,
Shuyi

**Comment by xihaoli** [comment]
Hi @liangshy3,

Thank you for your question. For the functional annotations scores (e.g. linsight or annotation principal components) used in STAAR/STAARpipeline, they have already been precomputed into the Phred-scale scores and are available in the [FAVOR Essential Database](https://doi.org/10.7910/DVN/1VGTJI). As such, you may download them from FAVOR and use them directly.

Best,
Xihao

**Comment by xihaoli** [comment]
Hi Shuyi,

Yes, if the range of a score is [0.033, 0.995], then it's not in Phred scale. The Phred-scaled score can be as large as 10 (top 10% across the genome), 20 (top 1%), 30 (top 0.1%), or higher.

Best,
Xihao

**Comment by liangshy3** [comment]
Hi Dr. Li,
Thank you for the clarification! Could you please advice on the way to calculate phred-scaled score for these variables? We encountered difficulties in handling the extreme large FAVOR dataset and R cannot handle such huge files. Are there any terminal tools that you used to get the phred score? Or does it make sense to calculate phred score by subsetting variants in FAVOR that are in our database and rank the subset data?
Thank you!
Shuyi

**Comment by xihaoli** [comment]
Hi Shuyi,

You may check the source code of [favorannotator](https://github.com/li-lab-genetics/favorannotator-rap), which includes [scripts](https://github.com/li-lab-genetics/favorannotator-rap/blob/main/resources/home/dnanexus/favorannotator.R) for downloading and annotating any given list of variants. Specifically, we used the [xsv](https://github.com/BurntSushi/xsv) tool to handle large annotation files efficiently.

Hope this helps.

Best,
Xihao

**Comment by liangshy3** [comment]
Hi Dr. Li,
Thank you for the guidance! The script is very helpful. But I'm still confused that the source code uses the raw functional scores while in the paper rank(score)/number of variants is used. 
Best,
Shuyi

**Comment by liangshy3** [comment]
Hi Dr. Li,
We would like to extract cadd, linsight, fathmm_xf, sift_val, polyphen2_hdiv_score, polyphen2_hvar_score, mutation_taster_score, and mutation_assessor_score from the FAVOR Full Database instead of the essential one. Are these also in phred scale in the Full Database?
Thanks again!
Shuyi

**Comment by liangshy3** [comment]
Hi Dr. Li,
Thank you for the detailed explanation! This is very helpful for understanding the structure of FAVOR.
Best,
Shuyi
